const REPLICATE_PROXY_URL = "https://itp-ima-replicate-proxy.web.app/api/create_n_get";
const MODEL = "google/nano-banana-2";

const form = document.querySelector("#prompt-form");
const promptInput = document.querySelector("#prompt");
const generateButton = document.querySelector("#generate-button");
const buttonLabel = generateButton.querySelector(".button-label");
const statusMessage = document.querySelector("#status");
const results = document.querySelector("#results");
const gallery = document.querySelector("#gallery");
const galleryStatus = document.querySelector("#gallery-status");
const galleryCount = document.querySelector("#gallery-count");

const database = firebase.initializeApp(window.firebaseConfig).firestore();
const imagesCollection = database.collection("generatedImages");

loadGallery();

form.addEventListener("submit", async (event) => {
  event.preventDefault();
  const prompt = promptInput.value.trim();
  if (!prompt) {
    promptInput.focus();
    return;
  }

  setLoading(true);
  setStatus("Sending your prompt to Nano Banana 2…");
  results.replaceChildren();

  try {
    const response = await fetch(REPLICATE_PROXY_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: MODEL,
        input: { prompt },
      }),
    });

    const prediction = await response.json().catch(() => null);
    if (!response.ok) {
      throw new Error(getErrorMessage(prediction, response.status));
    }

    const imageUrls = getImageUrls(prediction);
    if (imageUrls.length === 0) {
      throw new Error(getErrorMessage(prediction) || "The model response did not include an image.");
    }

    renderImages(imageUrls, prompt);
    setStatus("Image generated. Saving it to the shared gallery…");
    await saveImages(imageUrls, prompt);
    setStatus(imageUrls.length === 1 ? "Your image is ready and saved." : `${imageUrls.length} images are ready and saved.`);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Something went wrong. Please try again.";
    const imageWasGenerated = results.childElementCount > 0;
    setStatus(
      imageWasGenerated ? `Image generated, but it couldn't be saved: ${message}` : message,
      "error",
    );
  } finally {
    setLoading(false);
  }
});

function setLoading(isLoading) {
  generateButton.disabled = isLoading;
  promptInput.disabled = isLoading;
  buttonLabel.textContent = isLoading ? "Generating…" : "Submit";
}

function setStatus(message, kind = "info") {
  statusMessage.textContent = message;
  statusMessage.dataset.kind = kind;
}

function getImageUrls(prediction) {
  const output = prediction?.output;
  const values = Array.isArray(output) ? output : [output];
  return values
    .map((value) => (typeof value === "string" ? value : value?.url))
    .filter((value) => typeof value === "string" && /^https?:\/\//i.test(value));
}

function getErrorMessage(payload, statusCode) {
  const detail = payload?.detail ?? payload?.error;
  const message = typeof detail === "string" ? detail : detail?.message;
  if (message) return message;
  if (statusCode) return `The image request failed (HTTP ${statusCode}). Please try again.`;
  return payload?.status === "failed" ? "The model could not generate that image. Try another prompt." : "";
}

function renderImages(imageUrls, prompt) {
  for (const [index, url] of imageUrls.entries()) {
    const figure = document.createElement("figure");
    figure.className = "result-card";

    const image = document.createElement("img");
    image.src = url;
    image.alt = `Generated image for: ${prompt}`;
    image.loading = "lazy";
    figure.append(image);

    const caption = document.createElement("figcaption");
    const link = document.createElement("a");
    link.href = url;
    link.target = "_blank";
    link.rel = "noopener noreferrer";
    link.textContent = `Open image ${index + 1} in a new tab`;
    caption.append(link);
    figure.append(caption);
    results.append(figure);
  }
}

async function saveImages(imageUrls, prompt) {
  await Promise.all(imageUrls.map((imageUrl) => imagesCollection.add({
    prompt,
    imageUrl,
    model: MODEL,
    createdAt: firebase.firestore.FieldValue.serverTimestamp(),
  })));
}

function loadGallery() {
  imagesCollection
    .orderBy("createdAt", "desc")
    .limit(30)
    .onSnapshot((snapshot) => {
      gallery.replaceChildren();
      galleryCount.textContent = `${snapshot.size} ${snapshot.size === 1 ? "image" : "images"}`;

      if (snapshot.empty) {
        galleryStatus.textContent = "No images yet. Submit a prompt to make the first one.";
        return;
      }

      galleryStatus.textContent = "Recent images generated by the community.";
      snapshot.forEach((document) => renderGalleryImage(document.data()));
    }, (error) => {
      galleryStatus.textContent = `The shared gallery couldn't be loaded: ${error.message}`;
      galleryStatus.dataset.kind = "error";
    });
}

function renderGalleryImage(imageData) {
  const card = document.createElement("figure");
  card.className = "gallery-card";

  const imageLink = document.createElement("a");
  imageLink.href = imageData.imageUrl;
  imageLink.target = "_blank";
  imageLink.rel = "noopener noreferrer";

  const image = document.createElement("img");
  image.src = imageData.imageUrl;
  image.alt = `Generated image: ${imageData.prompt}`;
  image.loading = "lazy";
  imageLink.append(image);
  card.append(imageLink);

  const caption = document.createElement("figcaption");
  const prompt = document.createElement("p");
  prompt.className = "gallery-prompt";
  prompt.textContent = imageData.prompt;
  caption.append(prompt);

  if (imageData.createdAt?.toDate) {
    const date = document.createElement("time");
    const createdAt = imageData.createdAt.toDate();
    date.dateTime = createdAt.toISOString();
    date.textContent = createdAt.toLocaleString();
    caption.append(date);
  }

  card.append(caption);
  gallery.append(card);
}
