const REPLICATE_PROXY_URL = "https://itp-ima-replicate-proxy.web.app/api/create_n_get";
const MODEL = "google/nano-banana-2";

const form = document.querySelector("#prompt-form");
const promptInput = document.querySelector("#prompt");
const generateButton = document.querySelector("#generate-button");
const buttonLabel = generateButton.querySelector(".button-label");
const statusMessage = document.querySelector("#status");
const gallery = document.querySelector("#gallery");
const galleryStatus = document.querySelector("#gallery-status");
const galleryCount = document.querySelector("#gallery-count");
const currentMakerStatus = document.querySelector("#current-maker");
const galleryCards = new Map();
const currentMaker = window.prompt("What's your name?")?.trim() ?? "";

const database = firebase.initializeApp(window.firebaseConfig).firestore();
const imagesCollection = database.collection("generatedImages");
let activeDrag = null;
let highestZIndex = 0;

currentMakerStatus.textContent = currentMaker
  ? `Creating as ${currentMaker}. Only pictures with this name can be moved in this browser session.`
  : "No name entered. You can browse, but must reload to create or move pictures.";
loadGallery();

form.addEventListener("submit", async (event) => {
  event.preventDefault();
  const prompt = promptInput.value.trim();
  if (!prompt) {
    promptInput.focus();
    return;
  }
  if (!currentMaker) {
    setStatus("Reload the page and enter your name before submitting a prompt.", "error");
    return;
  }

  setLoading(true);
  setStatus("Sending your prompt to Nano Banana 2…");
  let imageWasGenerated = false;

  try {
    const response = await fetch(REPLICATE_PROXY_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model: MODEL,
        input: { prompt },
      }),
    });

    const prediction = await response.json().catch(() => null);
    if (!response.ok) {
      throw new Error(getErrorMessage(prediction, response.status));
    }

    const imageUrls = getImageUrls(prediction);
    if (imageUrls.length === 0) {
      throw new Error(getErrorMessage(prediction) || "The model response did not include an image.");
    }

    imageWasGenerated = true;
    setStatus("Image generated. Saving it to the shared gallery…");
    await saveImages(imageUrls, prompt);
    setStatus(imageUrls.length === 1 ? "Your image is ready and saved." : `${imageUrls.length} images are ready and saved.`);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Something went wrong. Please try again.";
    setStatus(
      imageWasGenerated ? `Image generated, but it couldn't be saved: ${message}` : message,
      "error",
    );
  } finally {
    setLoading(false);
  }
});

function setLoading(isLoading) {
  generateButton.disabled = isLoading;
  promptInput.disabled = isLoading;
  buttonLabel.textContent = isLoading ? "Generating…" : "Submit";
}

function setStatus(message, kind = "info") {
  statusMessage.textContent = message;
  statusMessage.dataset.kind = kind;
}

function getImageUrls(prediction) {
  const output = prediction?.output;
  const values = Array.isArray(output) ? output : [output];
  return values
    .map((value) => (typeof value === "string" ? value : value?.url))
    .filter((value) => typeof value === "string" && /^https?:\/\//i.test(value));
}

function getErrorMessage(payload, statusCode) {
  const detail = payload?.detail ?? payload?.error;
  const message = typeof detail === "string" ? detail : detail?.message;
  if (message) return message;
  if (statusCode) return `The image request failed (HTTP ${statusCode}). Please try again.`;
  return payload?.status === "failed" ? "The model could not generate that image. Try another prompt." : "";
}

async function saveImages(imageUrls, prompt) {
  const firstIndex = Math.random() * 1000;
  await Promise.all(imageUrls.map((imageUrl, index) => imagesCollection.add({
    prompt,
    imageUrl,
    model: MODEL,
    makerName: currentMaker,
    createdAt: firebase.firestore.FieldValue.serverTimestamp(),
    ...getInitialPosition(firstIndex + index),
  })));
}

function loadGallery() {
  imagesCollection
    .orderBy("createdAt", "desc")
    .onSnapshot((snapshot) => {
      const visibleIds = new Set();
      galleryCount.textContent = `${snapshot.size} ${snapshot.size === 1 ? "image" : "images"}`;

      if (snapshot.empty) {
        galleryStatus.textContent = "No images yet. Submit a prompt to make the first one.";
        return;
      }

      galleryStatus.textContent = "Recent images generated by the community.";
      snapshot.docs.forEach((document, index) => {
        visibleIds.add(document.id);
        renderGalleryImage(document.id, document.data(), index);
      });

      for (const [id, elements] of galleryCards) {
        if (!visibleIds.has(id)) {
          elements.card.remove();
          galleryCards.delete(id);
        }
      }
    }, (error) => {
      galleryStatus.textContent = `The shared gallery couldn't be loaded: ${error.message}`;
      galleryStatus.dataset.kind = "error";
    });
}

function renderGalleryImage(id, imageData, index) {
  let elements = galleryCards.get(id);
  if (!elements) {
    elements = createGalleryCard(id);
    galleryCards.set(id, elements);
  }

  elements.imageLink.href = imageData.imageUrl;
  elements.image.src = imageData.imageUrl;
  elements.image.alt = `Generated image: ${imageData.prompt}`;
  elements.prompt.textContent = imageData.prompt;
  const makerName = typeof imageData.makerName === "string" ? imageData.makerName : "";
  elements.maker.textContent = makerName ? `Made by ${makerName}` : "Maker not recorded";
  elements.card.dataset.makerName = makerName;
  elements.card.classList.toggle("is-owned", Boolean(currentMaker) && makerName === currentMaker);
  elements.card.setAttribute(
    "aria-label",
    `Generated image: ${imageData.prompt}. Made by ${makerName || "unknown"}.${makerName === currentMaker ? " Use arrow keys to move." : ""}`,
  );

  if (imageData.createdAt?.toDate) {
    const createdAt = imageData.createdAt.toDate();
    elements.date.dateTime = createdAt.toISOString();
    elements.date.textContent = createdAt.toLocaleString();
    elements.date.hidden = false;
  } else {
    elements.date.hidden = true;
  }

  if (activeDrag?.id !== id) {
    const position = hasPosition(imageData) ? imageData : getInitialPosition(index);
    positionCard(elements.card, position.x, position.y);
  }

  elements.card.style.zIndex = String(++highestZIndex);
  gallery.append(elements.card);
}

function createGalleryCard(id) {
  const card = document.createElement("figure");
  card.className = "gallery-card";
  card.tabIndex = 0;
  card.setAttribute("role", "group");

  const imageLink = document.createElement("a");
  imageLink.target = "_blank";
  imageLink.rel = "noopener noreferrer";
  imageLink.draggable = false;

  const image = document.createElement("img");
  image.loading = "lazy";
  image.draggable = false;
  imageLink.append(image);
  card.append(imageLink);

  const caption = document.createElement("figcaption");
  const prompt = document.createElement("p");
  prompt.className = "gallery-prompt";
  const maker = document.createElement("p");
  maker.className = "gallery-maker";
  const date = document.createElement("time");
  caption.append(prompt, maker, date);
  card.append(caption);

  card.addEventListener("pointerdown", (event) => startDrag(event, id, card), true);
  card.addEventListener("dragstart", (event) => event.preventDefault());
  card.addEventListener("pointermove", moveDrag);
  card.addEventListener("pointerup", finishDrag);
  card.addEventListener("pointercancel", finishDrag);
  card.addEventListener("click", (event) => {
    if (card.dataset.suppressClick === "true") {
      event.preventDefault();
      delete card.dataset.suppressClick;
    }
  });
  const elements = { card, imageLink, image, prompt, maker, date };
  card.addEventListener("keydown", (event) => moveCardWithKeyboard(event, id, card));
  return elements;
}

function startDrag(event, id, card) {
  if (!event.isPrimary || event.button !== 0) return;
  if (!currentMaker || card.dataset.makerName !== currentMaker) {
    galleryStatus.textContent = currentMaker
      ? `Only ${card.dataset.makerName || "the recorded maker"} can move this picture.`
      : "Reload the page and enter your name before moving pictures.";
    return;
  }

  const boardRect = gallery.getBoundingClientRect();
  const cardRect = card.getBoundingClientRect();
  activeDrag = {
    id,
    card,
    pointerId: event.pointerId,
    boardRect,
    cardWidth: cardRect.width,
    cardHeight: cardRect.height,
    startX: event.clientX,
    startY: event.clientY,
    moved: false,
  };
  card.setPointerCapture(event.pointerId);
  card.classList.add("is-dragging");
  card.style.zIndex = String(++highestZIndex);
}

function moveDrag(event) {
  if (!activeDrag || event.pointerId !== activeDrag.pointerId) return;

  const deltaX = event.clientX - activeDrag.startX;
  const deltaY = event.clientY - activeDrag.startY;
  if (!activeDrag.moved && Math.hypot(deltaX, deltaY) < 3) return;

  activeDrag.moved = true;
  const position = getNormalizedPosition(
    event.clientX - activeDrag.boardRect.left,
    event.clientY - activeDrag.boardRect.top,
    activeDrag.boardRect,
    activeDrag.cardWidth,
    activeDrag.cardHeight,
  );
  positionCard(activeDrag.card, position.x, position.y);
}

async function finishDrag(event) {
  if (!activeDrag || event.pointerId !== activeDrag.pointerId) return;

  const drag = activeDrag;
  activeDrag = null;
  drag.card.classList.remove("is-dragging");

  if (!drag.moved) return;

  drag.card.dataset.suppressClick = "true";
  const position = {
    x: Number.parseFloat(drag.card.dataset.x),
    y: Number.parseFloat(drag.card.dataset.y),
  };

  try {
    await imagesCollection.doc(drag.id).update(position);
    galleryStatus.textContent = "Shared image position updated.";
    galleryStatus.dataset.kind = "info";
  } catch (error) {
    galleryStatus.textContent = `The image moved here but its shared position couldn't be saved: ${error.message}`;
    galleryStatus.dataset.kind = "error";
  }
}

async function moveCardWithKeyboard(event, id, card) {
  const directions = {
    ArrowUp: [0, -1],
    ArrowDown: [0, 1],
    ArrowLeft: [-1, 0],
    ArrowRight: [1, 0],
  };
  const direction = directions[event.key];
  if (!direction) return;
  if (!currentMaker || card.dataset.makerName !== currentMaker) {
    event.preventDefault();
    galleryStatus.textContent = currentMaker
      ? `Only ${card.dataset.makerName || "the recorded maker"} can move this picture.`
      : "Reload the page and enter your name before moving pictures.";
    return;
  }

  event.preventDefault();
  const rect = gallery.getBoundingClientRect();
  const cardRect = card.getBoundingClientRect();
  const currentX = Number.parseFloat(card.dataset.x);
  const currentY = Number.parseFloat(card.dataset.y);
  const stepX = 24 / rect.width;
  const stepY = 24 / rect.height;
  const position = getNormalizedPosition(
    (currentX + direction[0] * stepX) * rect.width,
    (currentY + direction[1] * stepY) * rect.height,
    rect,
    cardRect.width,
    cardRect.height,
  );
  positionCard(card, position.x, position.y);

  try {
    await imagesCollection.doc(id).update(position);
    galleryStatus.textContent = "Shared image position updated.";
    galleryStatus.dataset.kind = "info";
  } catch (error) {
    galleryStatus.textContent = `The image moved here but its shared position couldn't be saved: ${error.message}`;
    galleryStatus.dataset.kind = "error";
  }
}

function positionCard(card, x, y) {
  card.dataset.x = String(x);
  card.dataset.y = String(y);
  card.style.left = `${x * 100}%`;
  card.style.top = `${y * 100}%`;
}

function getNormalizedPosition(centerX, centerY, boardRect, cardWidth, cardHeight) {
  const halfWidth = Math.min(cardWidth / 2, boardRect.width / 2);
  const halfHeight = Math.min(cardHeight / 2, boardRect.height / 2);
  const x = Math.min(
    Math.max(centerX / boardRect.width, halfWidth / boardRect.width),
    1 - halfWidth / boardRect.width,
  );
  const y = Math.min(
    Math.max(centerY / boardRect.height, halfHeight / boardRect.height),
    1 - halfHeight / boardRect.height,
  );
  return { x, y };
}

function hasPosition(imageData) {
  return Number.isFinite(imageData.x) && Number.isFinite(imageData.y);
}

function getInitialPosition(index) {
  const angle = index * 2.399963229728653;
  const radius = Math.min(0.12 + Math.sqrt(index) * 0.075, 0.68);
  return {
    x: Math.min(Math.max(0.5 + Math.cos(angle) * radius, 0.08), 0.92),
    y: Math.min(Math.max(0.5 + Math.sin(angle) * radius, 0.08), 0.92),
  };
}
